### ISSUE TITLE
Problem to create a workspace and make it active

### ISSUE THREAD

**Issue by wumpz** [geosolutions-it/geoserver-manager#161]
Using the standard publishers it seems not to be possible to create an active workspace. The created workspace has to be activated after the creation.

I use geoserver-manager v.1.6 and am not able to create an active workspace using something like

new GeoServerRESTManager(...) .getPublisher().createWorkspace("testworkspace")

**Comment by drunkenpanda7** [comment]
do you really need it to be active? When i create a Workspace i never set it active and it works.

**Comment by wumpz** [comment]
First of all the workspace needs to be active to use styles that are workspace dependend. Second I need to set the option to prefix the layername by the workspace name (workspace:layer1). So is there another way to achieve this?

I want to make a complete config using geoserver-manager without the need to open geoservers browser page.

**Comment by wumpz** [comment]
Is there any progress on this?
