### ISSUE TITLE
Problem to publish the shp

### ISSUE THREAD

**Issue by shanyuk** [geosolutions-it/geoserver-manager#170]
String RESTURL = "http://localhost:8080/geoserver/nurc/wms";
	      String RESTUSER ="admin";
	      String RESTPW = "geoserver";
		  
	      GeoServerRESTPublisher publisher = new GeoServerRESTPublisher(RESTURL,RESTUSER,RESTPW);
	      boolean created = publisher.createWorkspace("Myworkspace");
	   
	      String storeName = "resttestshp";
          String layerName = "states";
          File zipFile = new ClassPathResource("resourse/states.zip").getFile();
	      boolean published = publisher.publishShp("Myworkspace", storeName, layerName, zipFile);

**Comment by shanyuk** [comment]
I have do it.

**Comment by simboss** [comment]
So can we close this one?
