### ISSUE TITLE
Release 1.7.1 ???

### ISSUE THREAD

**Issue by wumpz** [geosolutions-it/geoserver-manager#197]

**Comment by simboss** [comment]
PLz, use the group to communicate not issues.

We are planning to make a new release after FOSS4G, so it's beg of Sept.

**Comment by wumpz** [comment]
I do not think this is not a communication thing anymore but an issue, that there is no release after all. There are so many usefull pull requests from your users. 

Will there be a next release?

**Comment by wumpz** [comment]
Any comments here? Does this project need a maintainer?
