### ISSUE TITLE
why does it show “java.lang.NoSuchMethodError”？

### ISSUE THREAD

**Issue by shanyuk** [geosolutions-it/geoserver-manager#202]
My codes：
 try {
	            URL = new URL(RESTURL);
	            manager = new GeoServerRESTManager(URL, RESTUSER, RESTPW);
	            reader = manager.getReader();
	            publisher = manager.getPublisher();
	            System.out.print(reader.existGeoserver());
//	            List tt = (List) reader.getWorkspaceNames();
	        } catch (MalformedURLException e) {
	            e.printStackTrace();
	        **}**
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.httpclient.HttpConnectionManager.closeIdleConnections(J)V

**Comment by simboss** [comment]
Issues are not for questions, use the ML :)
