### ISSUE TITLE
Is this project active anymore?

### ISSUE THREAD

**Issue by wumpz** [geosolutions-it/geoserver-manager#222]
Are there alternative approaches somewhere documented?
Is there a preferred way of geoservers rest interface to be accessed?

**Comment by etj** [comment]
It depends on what you mean by "active".
We use the GeoServer-Manager library for some internal projects, and it has all the features we need at the moment. 
It has been used few months ago to test that the big REST refactoring in GeoServer still worked. 
I need some spare time to merge all the pending PRs indeed :|

**Comment by wumpz** [comment]
Many improvements of geoservers rest interface are not implemented. Workspace activation, style upload CSS and yaml, ...
