### ISSUE TITLE
Is this library still active?

### ISSUE THREAD

**Issue by exotfboy** [geosolutions-it/geoserver-manager#233]
### GeoServer Compatibility Matrix

 **GeoServer-Manager/GeoServer** | **2.6.x** |**2.7.x** |**2.8.x** |**2.9.x** 
-------------------------------- | ----------|----------|----------|---------
 **1.6.0** | Y | Y | P | P 
 **1.7.0** | N |  P | Y | Y 

The latest geoserver versoin is `2.17.x`, so I wonder if this repository is under development?

**Comment by alfonx** [comment]
I haven't seen any development in this repo for years sadly.
But I can confirm, that it is working with latest GeoServer 2.17.1

**Comment by exotfboy** [comment]
@alfonx  Thank you, I will have a try.

**Comment by simboss** [comment]
hi @exotfboy,
no we are not actively developing this library any longer.

We are happy to support anyone who would want to fork it and develop it further.
