### ISSUE TITLE
create new layer misses attributes

### ISSUE THREAD

**Issue by kissmd** [geosolutions-it/geoserver-manager#45]
Please add support to GSFeatureTypeEncoder to contain also layer attributes!

I cannot create new layers in geoserver 2.1.2 because there is no way to define layer attributes.
The server response is:  400: "Trying to create new feature type inside the store, but no attributes were specified"

If i fill every field on the GSFeatureTypeEncoder it will only transforms to like this: 
httpclient.wire.content - >> "<featureType><metadata /><keywords /><name>layer1</name><nativeCRS>EPSG:4326</nativeCRS><description>new layer</description><title>Layer1</title><enabled>true</enabled></featureType>"

But there should be also a part like this:
 <attributes>
<attribute><name>ver</name>
<minOccurs>1</minOccurs>
<maxOccurs>1</maxOccurs>
<nillable>false</nillable>
<binding>java.lang.Long</binding>
</attribute>
....
<attributes>

**Comment by mraleksanyan17** [comment]
My code this problem.
What can I do?

**Comment by shayneoneill** [comment]
Did you ever get an answer to this?
